### Basic Steps for developing a model with Pycaret

In [1]:
# conda install -c conda-forge lightgbm

In [2]:
from pycaret.datasets import get_data
data1 = get_data(dataset = 'traffic')

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,Rush Hour,traffic_volume
0,None,288.28,0.0,0.0,40,Clouds,1,5545
1,None,289.36,0.0,0.0,75,Clouds,0,4516
2,None,289.58,0.0,0.0,90,Clouds,0,4767
3,None,290.13,0.0,0.0,90,Clouds,0,5026
4,None,291.14,0.0,0.0,75,Clouds,0,4918

In [3]:
from pycaret.regression import *

In [4]:
dataset = setup(data = data1, target = 'traffic_volume',
                session_id = 438)

In [5]:
best = compare_models()

In [6]:
tuned_best = tune_model(estimator = best)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [7]:
final_model = finalize_model(estimator = tuned_best)

In [8]:
save_model(final_model, 'saved_lr_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/var/folders/_9/wkm0tqns0n53w3ytpgc_68kc0000gn/T/joblib),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['temp', 'rain_1h', 'snow_1h',
                                              'clouds_all', 'Rush Hour'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('onehot_encoding',
                  TransformerWrapper(include=['holiday', 'weather_main'],
                                     transformer=OneHotEncoder(cols=['holiday',
                                                                     'weather_main'],
                                                               handle_missing='return_nan',
                                                               use_cat_names=True))),
                 ('clean_column_names',
                  TransformerWrapper(transformer=CleanColumnNames())),
                 ('actual_estimator', LGBMRegressor(random_state=438))]),
 'saved_lr_model.pkl')

### Predictions

In [9]:
saved_model = load_model("../Pycaret/saved_lr_model")

Transformation Pipeline and Model Successfully Loaded

In [10]:
predictions = predict_model(saved_model, data = new_data)
predictions.head()

NameError: name 'new_data' is not defined